import { Component, OnInit } from '@angular/core';
import { MenuController } from '@ionic/angular';

@Component({
  selector: 'app-search',
  templateUrl: './search.page.html',
  styleUrls: ['./search.page.scss'],
})
export class SearchPage implements OnInit {

  municipios = [
    { nombre: "Acatic" },
    { nombre: "Acatlán de Juárez" },
    { nombre: "Ahualulco de Mercado" },
    { nombre: "Amacueca" },
    { nombre: "Amatitán" },
    { nombre: "Ameca" },
    { nombre: "Arandas" },
    { nombre: "Atemajac de Brizuela" },
    { nombre: "Atengo" },
    { nombre: "Atenguillo" },
    { nombre: "Atotonilco el Alto" },
    { nombre: "Atoyac" },
    { nombre: "Autlán de Navarro" },
    { nombre: "Ayotlán" },
    { nombre: "Ayutla" },
    { nombre: "Bolaños" },
    { nombre: "Cabo Corrientes" },
    { nombre: "Cañadas de Obregón" },
    { nombre: "Casimiro Castillo" },
    { nombre: "Chapala" },
    { nombre: "Chimaltitán" },
    { nombre: "Chiquilistlán" },
    { nombre: "Cihuatlán" },
    { nombre: "Cocula" },
    { nombre: "Colotlán" },
    { nombre: "Concepción de Buenos Aires" },
    { nombre: "Cuauitlán de García Barragán" },
    { nombre: "Cuautla" },
    { nombre: "Cuquío" },
    { nombre: "Degollado" },
    { nombre: "Ejutla" },
    { nombre: "El Arenal" },
    { nombre: "El Grullo" },
    { nombre: "El Limón" },
    { nombre: "El Salto" },
    { nombre: "Encarnación de Díaz" },
    { nombre: "Etzatlán" },
    { nombre: "Gómez Farías" },
    { nombre: "Guachinango" },
    { nombre: "Guadalajara" },
    { nombre: "Hostotipaquillo" },
    { nombre: "Huejúcar" },
    { nombre: "Huejuquilla el Alto" },
    { nombre: "Ixtlahuacán de los Membrillos" },
    { nombre: "Ixtlahuacán del Río" },
    { nombre: "Jalostotitlán" },
    { nombre: "Jamay" },
    { nombre: "Jesús María" },
    { nombre: "Jilotlán de los Dolores" },
    { nombre: "Jocotepec" },
    { nombre: "Juanacatlán" },
    { nombre: "Juchitlán" },
    { nombre: "La Barca" },
    { nombre: "Lagos de Moreno" },
    { nombre: "La Manzanilla de la Paz" },
    { nombre: "La Huerta" },
    { nombre: "Magdalena" },
    { nombre: "Mascota" },
    { nombre: "Mazamitla" },
    { nombre: "Mexticacán" },
    { nombre: "Mezquitic" },
    { nombre: "Mixtlán" },
    { nombre: "Ojuelos de Jalisco" },
    { nombre: "Ocotlán" },
    { nombre: "Pihuamo" },
    { nombre: "Poncitlán" },
    { nombre: "Puerto Vallarta" },
    { nombre: "Quitupan" },
    { nombre: "San Cristóbal de la Barranca" },
    { nombre: "San Diego de Alejandría" },
    { nombre: "San Gabriel" },
    { nombre: "San Ignacio Cerro Gordo" },
    { nombre: "San Juan de los Lagos" },
    { nombre: "San Juanito de Escobedo" },
    { nombre: "San Julián" },
    { nombre: "San Marcos" },
    { nombre: "San Martín de Bolaños" },
    { nombre: "San Martín Hidalgo" },
    { nombre: "San Miguel el Alto" },
    { nombre: "San Sebastián del Oeste" },
    { nombre: "Santa María de los Ángeles" },
    { nombre: "Santa María del Oro" },
    { nombre: "Sayula" },
    { nombre: "Tala" },
    { nombre: "Talpa de Allende" },
    { nombre: "Tamazula de Gordiano" },
    { nombre: "Tapalpa" },
    { nombre: "Tecalitlán" },
    { nombre: "Techaluta de Montenegro" },
    { nombre: "Tecolotlán" },
    { nombre: "Tenamaxtlán" },
    { nombre: "Teocaltiche" },
    { nombre: "Teocuitatlán de Corona" },
    { nombre: "Tepatitlán de Morelos" },
    { nombre: "Tequila" },
    { nombre: "Teuchitlán" },
    { nombre: "Tizapán el Alto" },
    { nombre: "Tlajomulco de Zúñiga" },
    { nombre: "Tlaquepaque" },
    { nombre: "Tolimán" },
    { nombre: "Tomatlán" },
    { nombre: "Tonalá" },
    { nombre: "Tonaya" },
    { nombre: "Tonila" },
    { nombre: "Totatiche" },
    { nombre: "Tototlán" },
    { nombre: "Tuxcacuesco" },
    { nombre: "Tuxcueca" },
    { nombre: "Tuxpan" },
    { nombre: "Unión de San Antonio" },
    { nombre: "Unión de Tula" },
    { nombre: "Valle de Guadalupe" },
    { nombre: "Valle de Juárez" },
    { nombre: "Villa Corona" },
    { nombre: "Villa Guerrero" },
    { nombre: "Villa Hidalgo" },
    { nombre: "Villa Purificación" },
    { nombre: "Yahualica de González Gallo" },
    { nombre: "Zacoalco de Torres" },
    { nombre: "Zapopan" },
    { nombre: "Zapotiltic" },
    { nombre: "Zapotitlán de Vadillo" },
    { nombre: "Zapotlán del Rey" },
    { nombre: "Zapotlanejo" },
    { nombre: "Zapotlán el Grande " },
  ];

  animales = [
    { tipo: "Perro" },
    { tipo: "Gato" },
  ];

  reportes = [
    { tipo: "Perdido" },
    { tipo: "Encontrado" },
    { tipo: "Adopcion" },
  ];

  constructor(private menu: MenuController) { }

  ngOnInit() {
  }

  closeMenu() {
    this.menu.close();
  }

}
